version: '3.9'
services:
  gateway:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - booking-service
    environment:
      - NODE_ENV=production

  auth-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/auth-service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Fardeen@1821
      - POSTGRES_DB=mahal_booking
       POSTGRES_HOST=auth-db
    depends_on:
      - auth-db

  booking-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/booking-service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://booking-db:27017/booking-service
    depends_on:
      - booking-db

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fardeen@1821
      POSTGRES_DB: mahal_booking
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  booking-db:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - booking-db-data:/data/db

volumes:
  auth-db-data:
  booking-db-data:
